In [ ]:
# 1- How can you perform word tokenization using NLTK

import nltk
from nltk.tokenize import  word_tokenize
nltk.download('punkt_tab')

from nltk.tokenize import word_tokenize

text = "This is an example sentence for word tokenization."
tokens = word_tokenize(text)

print(tokens)


['This', 'is', 'an', 'example', 'sentence', 'for', 'word', 'tokenization', '.']


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [ ]:
# 2- How can you perform sentence tokenization using NLTK


from nltk.tokenize import sent_tokenize

text = "This is an example sentence. It contains multiple sentences."
sentences = sent_tokenize(text)

print(sentences)

['This is an example sentence.', 'It contains multiple sentences.']


In [ ]:
# 3- How can you remove stopwords from a sentence

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt_tab')



def remove_stopwords(sentences):
  token=word_tokenize(sentences)
  stop_words = set(stopwords.words('english'))
  filtered_sentence = [w for w in token if not w.lower() in stop_words]
  return filtered_sentence


sentence = """If you're visiting this page, you're likely here because you're searching for a random sentence. Sometimes a random word just isn't enough, and that is where the random sentence generator comes into play. By inputting the desired number, you can make a list of as many random sentences as you want or need. Producing random sentences can be helpful in a number of different ways. """
filtered_sentence = remove_stopwords(sentence)

print(filtered_sentence)


["'re", 'visiting', 'page', ',', "'re", 'likely', "'re", 'searching', 'random', 'sentence', '.', 'Sometimes', 'random', 'word', "n't", 'enough', ',', 'random', 'sentence', 'generator', 'comes', 'play', '.', 'inputting', 'desired', 'number', ',', 'make', 'list', 'many', 'random', 'sentences', 'want', 'need', '.', 'Producing', 'random', 'sentences', 'helpful', 'number', 'different', 'ways', '.']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [ ]:
# How can you perform stemming on a word

import nltk
from nltk.stem import PorterStemmer

# Download NLTK data
nltk.download('punkt')

# Create a Porter Stemmer object
stemmer = PorterStemmer()

# Define a word to stem
print("__________________")
word = "running"

# Perform stemming
stemmed_word = stemmer.stem(word)

print(stemmed_word)  # Output: run

__________________
run


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
#  How can you perform lemmatization on a word
import nltk
from nltk.stem import WordNetLemmatizer


nltk.download('wordnet')

# Initialize the lemmatizer
lemmatizer = WordNetLemmatizer()

# Perform lemmatization
word = "Running"
lemma = lemmatizer.lemmatize(word)

print(lemma)

Running


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [1]:
# 6 -  How can you normalize a text by converting it to lowercase and removing punctuation




import re
import string

def normalize_text(text):
    # Convert to lowercase
    text = text.lower()

    # Remove punctuation
    text = re.sub('['+string.punctuation+']', '', text)

    return text

# Test the function
text = "Hello, World! How's it going?"
normalized_text = normalize_text(text)
print(normalized_text)

hello world hows it going


In [1]:
# 7-  How can you create a co-occurrence matrix for words in a corpus



from collections import Counter
from itertools import combinations
import numpy as np

def create_cooccurrence_matrix(corpus, window_size=2):
    # Tokenize and preprocess the corpus
    tokens = [word.lower() for word in corpus.split()]

    # Create vocabulary
    vocabulary = list(set(tokens))
    vocab_index = {word: idx for idx, word in enumerate(vocabulary)}

    # Initialize the matrix
    vocab_size = len(vocabulary)
    cooccurrence_matrix = np.zeros((vocab_size, vocab_size), dtype=np.int32)


    # Populate the matrix
    for i, word in enumerate(tokens):
        # Determine the context window
        start = max(0, i - window_size)
        end = min(len(tokens), i + window_size + 1)
        context = tokens[start:i] + tokens[i+1:end]

        for other_word in context:
            cooccurrence_matrix[vocab_index[word]][vocab_index[other_word]] += 1

    return cooccurrence_matrix, vocabulary



# Example corpus
corpus = "The quick brown fox jumps over the lazy dog. The dog was quick."
matrix, vocab = create_cooccurrence_matrix(corpus)

# Display the results...
print("Vocabulary:", vocab)
print("Co-occurrence Matrix:")
print(matrix)



Vocabulary: ['fox', 'dog', 'over', 'quick.', 'dog.', 'quick', 'was', 'lazy', 'the', 'jumps', 'brown']
Co-occurrence Matrix:
[[0 0 1 0 0 1 0 0 0 1 1]
 [0 0 0 1 1 0 1 0 1 0 0]
 [1 0 0 0 0 0 0 1 1 1 0]
 [0 1 0 0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 1 2 0 0]
 [1 0 0 0 0 0 0 0 1 0 1]
 [0 1 0 1 0 0 0 0 1 0 0]
 [0 0 1 0 1 0 0 0 2 0 0]
 [0 1 1 0 2 1 1 2 0 1 1]
 [1 0 1 0 0 0 0 0 1 0 1]
 [1 0 0 0 0 1 0 0 1 1 0]]


In [2]:
# : How can you apply a regular expression to extract all email addresses from a text

import re

def extract_email_addresses(text):
    """
    Extracts all email addresses from a given text.

    Args:
        text (str): The text to extract email addresses from.

    Returns:
        list: A list of extracted email addresses.
    """
    # Regular expression pattern to match email addresses
    pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'

    # Find all matches of the pattern in the text
    email_addresses = re.findall(pattern, text)

    return email_addresses


# Example usage
text = "Contact me at SuryanshChourasiya9993@gmail.com for more information."
email_addresses = extract_email_addresses(text)

print("Extracted Email Addresses:")
for email in email_addresses:
    print(email)









Extracted Email Addresses:
SuryanshChourasiya9993@gmail.com


In [7]:
# : How can you perform word embedding using Word2Vec


!pip install gensim

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import nltk

nltk.download('punkt_tab')
nltk.download('stopwords')
sentences = [
    "This is an example sentence.",
    "Word2Vec is a popular technique.",
    "It represents words as vectors.",
    # Add more sentences here...
]

stop_words = set(stopwords.words('english'))

tokenized_sentences = []
for sentence in sentences:
    tokens = word_tokenize(sentence.lower())
    tokens = [token for token in tokens if token not in stop_words]
    tokenized_sentences.append(tokens)



[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [8]:
from gensim.models import Word2Vec

model = Word2Vec(tokenized_sentences, vector_size=100, window=5, min_count=1)

In [9]:
# Get the word vector for a specific word
word_vector = model.wv['example']

# Compute the similarity between two words
similarity = model.wv.similarity('example', 'sentence')

print(f"Word Vector: {word_vector}")
print(f"Similarity: {similarity}")

Word Vector: [-9.5785465e-03  8.9431154e-03  4.1650687e-03  9.2347348e-03
  6.6435025e-03  2.9247368e-03  9.8040197e-03 -4.4246409e-03
 -6.8033109e-03  4.2273807e-03  3.7290000e-03 -5.6646108e-03
  9.7047603e-03 -3.5583067e-03  9.5494064e-03  8.3472609e-04
 -6.3384566e-03 -1.9771170e-03 -7.3770545e-03 -2.9795230e-03
  1.0416972e-03  9.4826873e-03  9.3558477e-03 -6.5958775e-03
  3.4751510e-03  2.2755705e-03 -2.4893521e-03 -9.2291720e-03
  1.0271263e-03 -8.1657059e-03  6.3201892e-03 -5.8000805e-03
  5.5354391e-03  9.8337233e-03 -1.6000033e-04  4.5284927e-03
 -1.8094003e-03  7.3607611e-03  3.9400971e-03 -9.0103243e-03
 -2.3985039e-03  3.6287690e-03 -9.9568366e-05 -1.2012708e-03
 -1.0554385e-03 -1.6716016e-03  6.0495257e-04  4.1650953e-03
 -4.2527914e-03 -3.8336217e-03 -5.2816868e-05  2.6935578e-04
 -1.6880632e-04 -4.7855065e-03  4.3134023e-03 -2.1719194e-03
  2.1035396e-03  6.6652300e-04  5.9696771e-03 -6.8423809e-03
 -6.8157101e-03 -4.4762576e-03  9.4358288e-03 -1.5918827e-03
 -9.4292425

In [12]:
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

#  How can you use Doc2Vec to embed documents

documents = [
    "This is an example document.",
    "Doc2Vec is a popular technique.",
    "It represents documents as vectors.",

]

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import nltk

nltk.download('punkt_tab')
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

# Prepare tagged documents
tagged_documents = []
for i, document in enumerate(documents):
    tokens = word_tokenize(document.lower())
    tokens = [token for token in tokens if token not in stop_words]
    tagged_documents.append(TaggedDocument(tokens, [i]))

from gensim.models import Doc2Vec

# Train the Doc2Vec model using tagged documents
model = Doc2Vec(tagged_documents, vector_size=100, window=5, min_count=1)



[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [16]:
# Get the document vector for a specific document
document_vector = model.infer_vector(tokenized_documents[0])

print(f"Document Vector: {document_vector}")

Document Vector: [-2.0091657e-03 -4.2069246e-04  1.6459254e-04  2.9977339e-03
  3.8319090e-03  1.9660019e-03  1.7960397e-04 -4.2669019e-03
 -9.9116319e-04 -1.7483237e-03  1.9438697e-03  3.0918012e-03
  3.1804179e-03 -4.7748806e-03  4.0108690e-04 -4.6071382e-03
 -4.3823561e-03  1.9474913e-03  1.5656597e-03  4.7103604e-03
 -1.8685132e-03  2.4110994e-03 -4.2760759e-03  3.9977375e-03
  3.0885218e-03 -3.7351253e-03  4.5689349e-03 -6.9842441e-05
 -4.1438732e-03  3.2020384e-03  2.1396691e-03 -3.2261342e-03
 -2.7701306e-05 -2.7850608e-03 -3.1294865e-03 -1.3278215e-03
 -4.4973223e-03  2.6314429e-03 -4.8071281e-03  2.5521265e-03
  1.5982421e-03 -2.7526307e-03 -3.4276766e-03 -3.2692000e-03
  3.1239316e-03 -2.4981136e-04 -1.3219453e-03  2.7516210e-03
  5.9936830e-04  1.1040124e-03  5.6942273e-04  3.9878911e-03
 -2.0587354e-04  3.7459752e-03  2.0634721e-03  4.3965881e-03
  3.4764674e-03 -1.2699403e-03 -1.3245206e-03  4.4343052e-03
 -1.3789298e-03  1.7159277e-03  1.1985934e-03 -2.5687625e-03
  3.524

In [20]:
# How can you perform part-of-speech tagging


import nltk
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger')


from nltk.tokenize import word_tokenize

sentence = "This is an example sentence."
tokens = word_tokenize(sentence)

from nltk import pos_tag

pos_tags = pos_tag(tokens)

print(f"POS Tags: {pos_tags}")



[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


POS Tags: [('This', 'DT'), ('is', 'VBZ'), ('an', 'DT'), ('example', 'NN'), ('sentence', 'NN'), ('.', '.')]


In [21]:

# Finding Similarity between Two Sentences using Cosine Similarity


from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from gensim.models import Word2Vec
from scipy import spatial

# Tokenize the sentences
sentence1 = "This is an example sentence."
sentence2 = "This sentence is an example too."

tokens1 = word_tokenize(sentence1.lower())
tokens2 = word_tokenize(sentence2.lower())

# Remove stop words and punctuation
stop_words = set(stopwords.words('english'))

tokens1 = [token for token in tokens1 if token not in stop_words]
tokens2 = [token for token in tokens2 if token not in stop_words]

# Train a Word2Vec model
model = Word2Vec([tokens1, tokens2], vector_size=100, window=5, min_count=1)

# Get the vector representations of the sentences
vector1 = sum([model.wv[token] for token in tokens1])
vector2 = sum([model.wv[token] for token in tokens2])

# Calculate the cosine similarity
similarity = 1 - spatial.distance.cosine(vector1, vector2)

print(f"Cosine Similarity: {similarity}")

Cosine Similarity: 1.0


In [22]:
# Extracting Named Entities from a Sentence

import spacy

# Load the spaCy model
nlp = spacy.load('en_core_web_sm')

# Process the sentence
sentence = "Apple is a technology company founded by Steve Jobs."
doc = nlp(sentence)

# Extract named entities
named_entities = [(entity.text, entity.label_) for entity in doc.ents]

print(f"Named Entities: {named_entities}")



Named Entities: [('Apple', 'ORG'), ('Steve Jobs', 'PERSON')]


In [23]:
# Splitting a Large Document into Smaller Chunks of Text
def split_document_into_chunks(document, chunk_size=100):
    """
    Splits a large document into smaller chunks of text.

    Args:
        document (str): The large document to split.
        chunk_size (int, optional): The size of each chunk. Defaults to 100.

    Returns:
        list: A list of chunks.
    """
    chunks = []
    words = document.split()

    current_chunk = []
    current_chunk_size = 0

    for word in words:
        if current_chunk_size + len(word) > chunk_size:
            chunks.append(' '.join(current_chunk))
            current_chunk = [word]
            current_chunk_size = len(word)
        else:
            current_chunk.append(word)
            current_chunk_size += len(word)

    if current_chunk:
        chunks.append(' '.join(current_chunk))

    return chunks

# Example usage
document = "This is a large document that needs to be split into smaller chunks."
chunks = split_document_into_chunks(document)

print(f"Chunks: {chunks}")

Chunks: ['This is a large document that needs to be split into smaller chunks.']


In [24]:
# Calculating TF-IDF for a Set of Documents

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.datasets import fetch_20newsgroups

# Load the 20 newsgroups dataset
dataset = fetch_20newsgroups(shuffle=True, random_state=42)

# Create a TfidfVectorizer object
vectorizer = TfidfVectorizer(max_features=10000)

# Fit the vectorizer to the dataset and transform the data into TF-IDF vectors
tfidf_vectors = vectorizer.fit_transform(dataset.data)

print(f"TF-IDF Vectors Shape: {tfidf_vectors.shape}")

TF-IDF Vectors Shape: (11314, 10000)


In [25]:
# Applying Tokenization, Stopword Removal, and Stemming in One Go
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

def preprocess_text(text):
    """
    Applies tokenization, stopword removal, and stemming to the input text.

    Args:
        text (str): The input text.

    Returns:
        list: A list of preprocessed tokens.
    """
    # Tokenize the text
    tokens = word_tokenize(text.lower())

    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [token for token in tokens if token not in stop_words]

    # Apply stemming
    stemmer = PorterStemmer()
    tokens = [stemmer.stem(token) for token in tokens]